config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :hospitals do
    member do
      get :doctor
      post :add_doctor
    end
  

    resources :patients do
      resources :medicines
      collection do
        get :search_names
      end
      member do
        get :new_doctor
        post :add_doctor
        patch :waiting
        patch :doctor
        patch :xrays
        patch :surgery
        patch :paybill
        patch :leaving
        get :waiting
        get :doctor
        get :xrays
        get :surgery
        get :paybill
        get :leaving
        get :discharge
      end
    end
  end
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :treatable, polymorphic: true
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  validates :name, presence: true
  has_many :join_tables
  has_many :patients, through: :join_tables
  has_many :doctors, as: :treatable
end

app/models/join_table.rb
class JoinTable < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :patient
end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :patient
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validates :name, presence: true
  has_many :join_tables
  has_many :hospitals, through: :join_tables
  has_many :doctors, as: :treatable
  has_many :medicines
  scope :search_names, -> search {where( "name like ?", "%#{search}%") }
  before_create :send_patient_email

  def send_patient_email
    # PatientMailer.new_patient_email(self).deliver
  end
    
  include Workflow
  workflow do 
    state :waiting do
      event :doctor, transitions_to: :doctor
      event :xray, transitions_to: :xray
      event :surgery, transitions_to: :surgery
      event :leaving, transitions_to: :leaving
    end

    state :doctor do
      event :doctor, transitions_to: :doctor
      event :xray, transitions_to: :xray
      event :surgery, transitions_to: :surgery
      event :paybill, transitions_to: :paybill
    end

    state :xray do
      event :surgery, transitions_to: :surgery
      event :doctor, transitions_to: :doctor
      event :paybill, transitions_to: :paybill
    end

    state :surgery do
      event :doctor, transitions_to: :doctor
      event :xray, transitions_to: :xray
      event :paybill, transitions_to: :paybill
    end

    state :paybill do
      event :leaving, transitions_to: :leaving
    end

    state :leaving 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hospital = Hospital.all
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_filter :find_hospital, only:[:show,
    :edit,
    :update,
    :destroy,
    :doctor,
    :add_doctor]
  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.create hospital_params
    success = @hospital.save
    if success == true
      flash[:notice] = "You entered an acceptable name"
      redirect_to root_path
    else
      flash[:error] = "you need to enter an acceptable name"
      render :new
    end
  end

  def show
    @patients = @hospital.patients
    @doctors = @hospital.doctors
    @patient = @hospital.patients.where.not(workflow_state: "leaving")
    @patient_leaving = @hospital.patients.where(workflow_state: "leaving")
  end

  def update
    @hospital.update_attributes hospital_params
    redirect_to root_path
  end

  def doctor
    @doctor = @hospital.doctors.new
  end

  def add_doctor
    @doctor = @hospital.doctors.create doctor_params
    redirect_to hospital_path(@hospital)
  end

  private
  def hospital_params
    params.require(:hospital).permit(:name, :address)
  end

  def find_hospital
    @hospital = Hospital.find params[:id]
  end
  
  def doctor_params
    params.require(:doctor).permit(:name)
  end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_filter :find_hospital
  before_filter :find_patient

  def new
    @medicine = Medicine.new
  end
  def create
    @medicine = @patient.medicines.create medicine_params
      success = @medicine.save
    if success == true
      flash[:notice] = "You entered a legal name"
    redirect_to hospital_patient_path(@hospital, @patient)
    else
      flash[:error] = "you need to enter a legal name"
      render :new
    end
  end

  private
     def find_patient
      @patient = Patient.find params[:patient_id]
    end

    def find_medicine
      @medicine = Medicine.find params[:id]
    end 

     def find_hospital
      @hospital = Hospital.find params[:hospital_id]
    end

    def medicine_params
      params.require(:medicine).permit(:name)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :find_hospital
  before_filter :find_patient, only:[:show,
    :edit,
    :update,
    :destroy,
    :doctor,
    :add_doctor,
    :new_doctor,
    :discharge]

  def index
    @patient = if params[:q]
      Patient.search_names params [:q]
    else
      Patient.all
    end
    respond_to do |format|
      format.js
    end
  end

  def new
    @patient = Patient.new 
    @hospitals = Hospital.all
  end

  def create
    @patient = Patient.create patient_params
    success = @patient.save
     if success == true
      flash[:notice] = "You entered an acceptable name"
      redirect_to hospital_path(@hospital)
    else
      flash[:error] = "you need to enter an acceptable name"
      render :new
    end
    
  end

  def show
    @doctor = @patient.doctors
    @medicine = @patient.medicines
  end

  def update
    @patient.update_attributes patient_params
    redirect_to hospital_path(@hospital)
  end

  def destroy
  end

  def new_doctor
    @doctor = @patient.doctors.new
  end

  def add_doctor
    @doctor = @patient.doctors.create doctor_params
    redirect_to hospital_patient_path(@hospital, @patient)
  end

  def doctor
    @patient = Patient.find params[:id]
    @patient.doctor!
    respond_to do |format|
      format.js
    end
  end

  def xrays
    @patient = Patient.find params[:id]
    @patient.xray!
    respond_to do |format|
      format.js
    end
  end

  def surgery
    @patient = Patient.find params[:id]
    @patient.surgery!
    respond_to do |format|
      format.js
    end
  end

  def paybill
    @patient = Patient.find params[:id]
    @patient.paybill!
    respond_to do |format|
      format.js
    end
  end

  def leaving
    @patient = Patient.find params[:id]
    @patient.leaving!
    respond_to do |format|
      format.js
    end
  end

  def search_names
    @patient = Patient.search_names params[:q]
  end

  def discharge
  end
  
  private
    def patient_params
      params.require(:patient).permit(:name,
        :address,
        :phone,
        :description,
        :hospital_id,
        :ad_info,
        {hospital_ids: []})
    end
    def doctor_params
      params.require(:doctor).permit(:name)
    end
    def find_hospital
      @hospital = Hospital.find params[:hospital_id]
    end
    def find_patient
      @patient = Patient.find params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/medicine_helper.rb
module MedicineHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/index.html.haml
%h1 Hospitals

=link_to "New Hospital", new_hospital_path
%br
%hr
-@hospital.each do |hospital|
  %br
  =link_to hospital.name, hospital_path(hospital)
  |
  =link_to "Edit", edit_hospital_path(hospital)

app/views/hospitals/_form.html.haml
%div.hospital
  =form_for @hospital do |f|
    = render 'layouts/error_messages', object: @hospital
    =f.label :name
    =f.text_field :name
    =f.label :address
    =f.text_field :address
    =f.submit

app/views/hospitals/doctor.html.haml
%h1 Add Doctor To #{@hospital.name} Hospital
=form_for [@hospital, @doctor], url: add_doctor_hospital_path(@hospital) do |f|
  =f.label :name
  =f.text_field :name
  = f.submit
=link_to "Cancel", hospital_path(@hospital)

app/views/hospitals/edit.html.haml
%h1 Edit
=render 'form'

app/views/hospitals/new.html.haml
%h1 new hospital
=render 'form'

app/views/hospitals/show.html.haml
%h1 #{@hospital.name}
%hr
=link_to "New Patient", new_hospital_patient_path(@hospital)
=link_to "New Doctor", doctor_hospital_path(@hospital)
%hr
%br
%h1 Patients
%br

.searchfunction
  =render 'patients/search'

%ul.patient
  -@patient.each_slice(10) do |patient, patient1, patient2, patient3, patient4, patient5, patient6, patient7, patient8, patient9|

    = render 'patients/patient', patient: patient if patient
    = render 'patients/patient', patient: patient1 if patient1
    = render 'patients/patient', patient: patient2 if patient2
    = render 'patients/patient', patient: patient3 if patient3
    = render 'patients/patient', patient: patient4 if patient4
    = render 'patients/patient', patient: patient5 if patient5
    = render 'patients/patient', patient: patient6 if patient6
    = render 'patients/patient', patient: patient7 if patient7
    = render 'patients/patient', patient: patient8 if patient8
    = render 'patients/patient', patient: patient9 if patient9

%ul
  .pagelink
    Page:
    %a{href: "javascript:void(0)"} 1
    %a{href: "javascript:void(0)"} 2
    %a{href: "javascript:void(0)"} 3
    %a{href: "javascript:void(0)"} 4
  %br

%hr
%h1 Doctors
-@doctors.each do |doctors|
  %br
  =doctors.name
%hr
%br
=link_to "Back To Hospital Page", root_path

%h1 Past Patients
-@patient_leaving.each do |patient|
  %br
  =link_to patient.name, hospital_patient_path(@hospital, patient)

app/views/layouts/_error_messages.html.haml
- object.errors.messages.each do |k, v|
  - v.each do |message|
    = k.capitalize
    = message
    %br

app/views/layouts/_flash.html.haml
- if flash[:notice]
  .notice= flash[:notice]
- else flash[:error]
  .error= flash[:error]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/flash' %>
<%= yield %>

</body>
</html>

app/views/medicines/_form.html.haml
=form_for [@hospital, @patient, @medicine] do |f|
  =f.label :name
  =f.text_field :name
  =f.submit

app/views/medicines/new.html.haml
%h1 New Medicine

=render 'form'

app/views/patients/_form.html.haml
=form_for [@hospital, @patient] do |f|
  = render 'layouts/error_messages', object: @patient
  =f.hidden_field :hospital_id, value: @hospital.id
  =f.label :name
  =f.text_field :name
  %br
  =f.label :address
  =f.text_field :address
  %br
  =f.label :phone
  =f.text_field :phone
  %br
  =f.label :description
  =f.text_area :description
  %br
  =f.label :email
  =f.text_field :email, placeholder: "Email"
  %br
  -@hospitals.each do |hospital|
    =check_box_tag 'patient[hospital_ids][]', hospital.id, false, {id: "hospital_id_#{hospital.id}"}
    =label_tag "hospital_id_#{hospital.id}", hospital.name
  %br
  =f.submit
%br
=link_to "Cancel", hospital_path(@hospital)
  

app/views/patients/_patient.html.haml
%li.patients{ class: "#{patient.workflow_state} patient patient_#{patient.id}"}
  =link_to patient.name, hospital_patient_path(@hospital, patient)
  (#{patient.workflow_state})
  %br
  - if patient.workflow_state == 'waiting'
    =link_to "See Doctor", "javascript:void(0);", class: "see_doctor change_workflow", patient_url: doctor_hospital_patient_path(@hospital, patient)
    |
    =link_to "Send to Xray", "javascript:void(0);", class: "go_to_xray change_workflow", patient_url: xrays_hospital_patient_path(@hospital, patient)
    |
    =link_to "Send to Surgery", "javascript:void(0);", class: "go_to_surgery change_workflow", patient_url: surgery_hospital_patient_path(@hospital, patient)
  - elsif patient.workflow_state == "doctor"
    =link_to "Send to Xray", "javascript:void(0);", class: "go_to_xray change_workflow", patient_url: xrays_hospital_patient_path(@hospital, patient)
    |
    =link_to "Send to Surgery", "javascript:void(0);", class: "go_to_surgery change_workflow", patient_url: surgery_hospital_patient_path(@hospital, patient)
    |
    =link_to "Send to Pay Bill", "javascript:void(0);", class: "pay_bill change_workflow", patient_url: paybill_hospital_patient_path(@hospital, patient)
  - elsif patient.workflow_state == "xray"
    =link_to "Send to Surgery", "javascript:void(0);", class: "go_to_surgery change_workflow", patient_url: surgery_hospital_patient_path(@hospital, patient)
    |
    =link_to "See Doctor", "javascript:void(0);", class: "see_doctor change_workflow", patient_url: doctor_hospital_patient_path(@hospital, patient)
    |
    =link_to "Send to Pay Bill", "javascript:void(0);", class: "pay_bill change_workflow", patient_url: paybill_hospital_patient_path(@hospital, patient)
  - elsif patient.workflow_state == "surgery"
    =link_to "Send to Xray", "javascript:void(0);", class: "go_to_xray change_workflow", patient_url: xrays_hospital_patient_path(@hospital, patient)
    |
    =link_to "See Doctor", "javascript:void(0);", class: "see_doctor change_workflow", patient_url: doctor_hospital_patient_path(@hospital, patient)
    |
    =link_to "Send to Pay Bill", "javascript:void(0);", class: "pay_bill change_workflow", patient_url: paybill_hospital_patient_path(@hospital, patient)
  - elsif patient.workflow_state == "paybill"
    =link_to "Leave Hospital", "javascript:void(0);", class: "leave change_workflow", patient_url: leaving_hospital_patient_path(@hospital, patient)

app/views/patients/_search.html.haml
= form_tag search_names_hospital_patients_path(@hospital), method: :get, remote: true
=text_field_tag "q", "", placeholder: "Search..."
= submit_tag "search"

app/views/patients/discharge.html.haml
=form_for [@hospital, @patient] do |f|
  =f.label :ad_info
  =f.text_field :ad_info
  %br
  =f.submit

app/views/patients/doctor.html.haml
%h1 Add Doctor
=form_for [@hospital, @patient, @doctor], url: add_doctor_hospital_patient_path(@hospital, @patient) do |f|
  =f.label :name
  =f.text_field :name
  = f.submit
=link_to "Cancel", hospital_patient_path(@hospital, @patient)

app/views/patients/doctor.js.erb
$("li.patient_" + "<%= @patient.id %>").replaceWith( "<%= escape_javascript(render(partial: 'patients/patient', locals: { patient: @patient})) %>" 
  )

app/views/patients/index.js.erb
$("ul.patient").html("");
<% @patient.each do |patient| %>
  $("ul.patient").append("<%= escape_javascript(render(partial: 'patients/patient', locals: {patient: patient})) %>");
<% end %>

app/views/patients/leaving.js.erb
window.location = "<%=discharge_hospital_patient_path(@hospital, @patient)%>"

app/views/patients/new.html.haml
%h1 New Patient
=render 'form'

app/views/patients/new_doctor.html.haml
%h1 Add Doctor
=form_for [@hospital, @patient, @doctor], url: add_doctor_hospital_patient_path(@hospital, @patient) do |f|
  =f.label :name
  =f.text_field :name
  = f.submit
=link_to "Cancel", hospital_patient_path(@hospital, @patient)

app/views/patients/paybill.js.erb
$("li.patient_" + "<%= @patient.id %>").replaceWith( "<%= escape_javascript(render(partial: 'patients/patient', locals: { patient: @patient})) %>" 
  )

app/views/patients/search_names.js.erb
 console.log("yay")
$("ul.patient").html("");
<% @patient.each do |patient| %>
  $("ul.patient").append("<%= escape_javascript(render(partial: 'patients/patient', locals: {patient: patient})) %>");
<% end %>

app/views/patients/show.html.haml
=link_to "New Doctor", new_doctor_hospital_patient_path(@hospital, @patient)
=link_to "New Medication", new_hospital_patient_medicine_path(@hospital, @patient)
%br
%h1 Patient
%br
=@patient.name
%br
=@patient.address
%br
%h3 Medications
-@medicine.each do |medicine|
  %br
  =medicine.name
%hr
%h1 Doctor
%br
-@doctor.each do |doctors|
  %br
  =doctors.name
%br
%hr
=link_to "Back", hospital_path(@hospital)

app/views/patients/surgery.js.erb
$("li.patient_" + "<%= @patient.id %>").replaceWith( "<%= escape_javascript(render(partial: 'patients/patient', locals: { patient: @patient})) %>" 
  )